aws_region      = "ap-south-1"
vpc_cidr        = "12.12.0.0/16"
vpc_name        = "demo-vpc"
subnet_cidr     = "10.10.1.0/24"
subnet_name     = "demo-subnet"
availability_zone = "ap-south-1a"
sg_name         = "demo-sg"
ami_id          = "ami-0f5ee92e2d63afc18" # Replace with a valid AMI ID for your region
instance_type   = "t2.micro"
key_name        = "ubuntu-pemkey"           # Replace with your actual SSH keypair name in AWS
instance_name   = "demo-ec2-instance"
